// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_refresh_token.sql

package repository

import (
	"context"
	"time"
)

const updateRefreshTokenExpiredAt = `-- name: UpdateRefreshTokenExpiredAt :exec
UPDATE refresh_token
SET expired_at = $2
WHERE token = $1
`

type UpdateRefreshTokenExpiredAtParams struct {
	Token     string
	ExpiredAt time.Time
}

func (q *Queries) UpdateRefreshTokenExpiredAt(ctx context.Context, arg UpdateRefreshTokenExpiredAtParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenExpiredAt, arg.Token, arg.ExpiredAt)
	return err
}
