// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_refresh_token.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateRefreshTokenExpiredAt = `-- name: UpdateRefreshTokenExpiredAt :exec
UPDATE refresh_token
SET expired_at = $2
WHERE id = $1
`

type UpdateRefreshTokenExpiredAtParams struct {
	ID        uuid.UUID
	ExpiredAt time.Time
}

func (q *Queries) UpdateRefreshTokenExpiredAt(ctx context.Context, arg UpdateRefreshTokenExpiredAtParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenExpiredAt, arg.ID, arg.ExpiredAt)
	return err
}
