#!/bin/bash

CURRENT_DIR=$(pwd)
APP=$1

# Read env in .env file
export $(cat .env | xargs)

cd internal/app/$APP/infra/store/sql/schema

DB_URL="postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_DATABASE?sslmode=disable"

echo "Running migrate up on $DB_URL"

goose postgres "$DB_URL" up

cd $CURRENT_DIR
