#!/bin/bash

# If --local then start dock-compose.local
if [[ "$1" == "--local" ]]; then
    docker-compose -f docker-compose.local.yml up --build -d

    # While loop until the database is up
    while ! pg_isready -h localhost -p 5432 -U postgres; do
        echo "Waiting for database to be ready..."
        sleep 1
    done
fi

air --build.cmd "go build -o bin/server cmd/webserver/*.go" --build.bin "./bin/server"
